#! /usr/bin/env python3

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import apt_pkg

from application import Application


apt_pkg.init()
application = Application()
application.run()
