#! /usr/bin/env python3

import os.path
import sys
import gettext
gettext.install("apteryx",
                localedir=os.path.join(os.path.dirname(sys.argv[0]), "locale"))

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import apt_pkg

from application import Application


apt_pkg.init()
application = Application()
application.run()
